//! ts-rs export test (ADR-004, 3.2).
//! Single source Rust -> `src/lib/domain/types.ts`.
//! Dijalankan via `cargo test export_types_ts`; hasil diverifikasi `pnpm check`.

use ts_rs::TS;

use crate::{
    commands::AppInfo,
    core::InstalledSource,
    data::datasources::extension::{
        ExtensionManifest, ManifestEntry, ManifestMeta, ZipPreview, ZipSourceCandidate,
    },
    domain::{
        BubbleBox, Chapter, Comment, Content, DownloadState, DownloadTask, GlossaryEntry, Hello,
        HistoryItem, Language, PageImageResult, PageTranslation, ReaderSettings, ReadingMode,
        SearchFilter, SourceId, Tag,
    },
};

#[test]
fn export_types_ts() {
    let cfg = ts_rs::Config::default();
    let decls: &[String] = &[
        Hello::decl(&cfg),
        AppInfo::decl(&cfg),
        Content::decl(&cfg),
        Chapter::decl(&cfg),
        PageImageResult::decl(&cfg),
        SearchFilter::decl(&cfg),
        ReaderSettings::decl(&cfg),
        ReadingMode::decl(&cfg),
        DownloadTask::decl(&cfg),
        DownloadState::decl(&cfg),
        BubbleBox::decl(&cfg),
        PageTranslation::decl(&cfg),
        GlossaryEntry::decl(&cfg),
        SourceId::decl(&cfg),
        Language::decl(&cfg),
        InstalledSource::decl(&cfg),
        ExtensionManifest::decl(&cfg),
        ManifestEntry::decl(&cfg),
        ManifestMeta::decl(&cfg),
        ZipSourceCandidate::decl(&cfg),
        ZipPreview::decl(&cfg),
        HistoryItem::decl(&cfg),
        Comment::decl(&cfg),
        Tag::decl(&cfg),
    ];

    let mut out = String::from(
        "// GENERATED by `cargo test export_types_ts` (ts-rs, ADR-004). Jangan edit manual.\n// Single source: `src-tauri/src/domain` (+ `AppInfo` commands).\n\n",
    );
    for decl in decls {
        out.push_str("export ");
        out.push_str(decl);
        out.push_str("\n\n");
    }

    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../src/lib/domain/types.ts");
    std::fs::write(&path, &out).unwrap();

    assert!(out.contains("type Content ="));
    assert!(out.contains("type Hello ="));
    assert!(out.contains("type AppInfo ="));
    assert!(out.contains("type InstalledSource ="));
    assert!(out.contains("type ExtensionManifest ="));
    assert!(out.contains("type ZipPreview ="));
    assert!(out.contains("type ZipSourceCandidate ="));
    assert!(out.contains("type HistoryItem ="));
    assert!(out.contains("type Comment ="));
    assert!(out.contains("type Tag ="));
}
