// GENERATED by `cargo test export_types_ts` (ts-rs, ADR-004). Jangan edit manual.
// Single source: `src-tauri/src/domain` (+ `AppInfo` commands).

export type Hello = { name: string, message: string, };

export type AppInfo = { name: string, version: string, backend: string, };

export type Content = { id: string, title: string, cover_url: string, source_id: string, upload_date: string | null, is_favorite: boolean, 
/**
 * Jumlah halaman (badge kartu); None = tak diketahui sumber ini.
 */
page_count: number | null, 
/**
 * Kode bahasa ISO (en/ja/zh/id); None = tak diketahui.
 */
language: string | null, };

export type Chapter = { id: string, content_id: string, title: string, order: number, is_external: boolean, external_url: string | null, };

export type PageImageResult = { "kind": "Cached", "value": string } | { "kind": "Remote", "value": string };

export type SearchFilter = { query: string, source_id: string | null, page: number, };

export type ReaderSettings = { mode: ReadingMode, right_to_left: boolean, };

export type ReadingMode = "Paginated" | "ContinuousScroll" | "Webtoon";

export type DownloadTask = { chapter_id: string, content_id: string, state: DownloadState, };

export type DownloadState = "Queued" | { "Downloading": { page: number, total: number, } } | "Paused" | "Completed" | { "Failed": string };

export type BubbleBox = { x: number, y: number, w: number, h: number, translated: string | null, };

export type PageTranslation = { page_index: number, bubbles: Array<BubbleBox>, };

export type GlossaryEntry = { source: string, target: string, };

export type SourceId = string;

export type Language = "En" | "Id" | "Zh" | { "Other": string };

export type InstalledSource = { id: string, version: string, base_url: string, installed: boolean, icon_url: string | null, 
/**
 * `ui.displayName` dari config sumber (nama tampil ala mobile).
 */
display_name: string | null, };

export type ExtensionManifest = { schemaVersion: number, minimumAppVersion: string, installableSources: Array<ManifestEntry>, };

export type ManifestEntry = { id: string, version: string, url: string, meta: ManifestMeta | null, checksum: string, };

export type ManifestMeta = { displayName: string, description: string, contentType: string, language: string, sizeKb: number, iconUrl: string | null, };

export type ZipSourceCandidate = { id: string, version: string, displayName: string | null, iconUrl: string | null, };

export type ZipPreview = { token: string, sources: Array<ZipSourceCandidate>, };

export type HistoryEntry = { content_id: string, 
/**
 * Halaman terakhir dibaca (1-based, ala `History.lastPage` mobile).
 */
position: bigint, 
/**
 * Terakhir dilihat, unix epoch detik (ala `History.lastViewed`).
 */
updated_at: bigint, };

